import Mathlib.Tactic

/-!
# ForgeLean.Scratch

Scratch space for candidate proofs generated by the system.
This file is overwritten by the proof search pipeline.
-/

-- Generated proofs will be inserted below by the lean_env service.
-- This file is ephemeral and should not be committed with real content.

example : True := trivial
